openapi: 3.0.0
info:
  title: VideoAnnotator API (Partial)
  version: 1.3.0
paths:
  /api/v1/jobs/{job_id}/artifacts:
    get:
      summary: Download Job Artifacts
      description: Streams a ZIP file containing all artifacts for a specific job.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the job.
      responses:
        '200':
          description: ZIP archive of job artifacts.
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '404':
          description: Job not found or artifacts not available.
        '500':
          description: Server error.
